routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/','PageController@index');
Route::middleware(['auth'])->group(function () {
    Route::resource('panel/user','UserController');
    Route::resource('panel/video', 'VideoController');
    Route::prefix('panel/')->group(function () {
        Route::post('video/upload', ['as' => 'panel.video.upload', 'uses' => 'UploadVideoController@addVideo']);
        Route::get('user/followers', 'PanelUserController@followers');
        Route::get('user/following', 'PanelUserController@following');
    });
    Route::prefix('u/{channel}/')->group(function () {
        Route::get('followers', 'PanelUserController@followers')->name('user.followers');
        Route::get('following', 'PanelUserController@following')->name('user.followings');
        Route::get('follow', ['as' => 'follow.channel', 'uses' => 'ChannelController@follow']);
        Route::get('unfollow', ['as' => 'unfollow.channel', 'uses' => 'ChannelController@unfollow']);
    });
});

Route::resource('/panel/category', 'CategoryController');

Route::prefix('/u/{name}/')->group(function () {
    Route::get('mostview', ['as' => 'channel.mostview', 'uses' => 'ChannelController@mostview']);
    Route::get('/', ['uses' => 'ChannelController@userChannel', 'as' => 'channel']);
    Route::get('mostlike', ['as' => 'channel.mostlike', 'uses' => 'ChannelController@mostLiked']);
});


Route::get('p/{slug}', 'SingleVideoController@show');
Route::get('p/{slug}/download','SingleVideoController@download');
Route::post('p/{slug}/viewplus','SingleVideoController@plusVideo');
Route::get('p/{slug}/like','SingleVideoController@like');
Route::get('p/{slug}/dislike','SingleVideoController@dislike');

/* -------------------Test Routes ---------------*/
Route::prefix('test')->group(function () {
    Route::get('datetime', 'HomeController@dateTime');
    Route::get('arrobj', 'HomeController@arrayObject');
    Route::get('curl','SingleVideoController@testt');
});

Auth::routes();

app/Http/Controllers/PanelUserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class PanelUserController extends Controller
{
    public function followers()
    {
        $user = auth()->user();
        $allFollowers =  $user->followers()->get();
        dd($allFollowers,$user);
        return view('panelUser.followers',compact('allFollowers'));
    }

    public function following()
    {
        $user = auth()->user();
        $allFollowings = $user->following()->get();
//        dd($allFollowings);
        return view('panelUser.followings',compact('allFollowings'));
    }

    function deleteFromFollowers($id){
//        $user->
    }
}

resources/views/panelUser/followers.blade.php
@extends('master')
@section('content')
    @include('Components.Swal')
    <div class="container-fluid bg-theme">
        <div class="row">
            <div class="col-md-12 col-xs-12 col-sm-12">
                <div class="img">
                    <a href="#">
                        <img height="200" width="200" class="figure-img p-3 br-50"
                             src="/images/profile.jpg" alt="">
                    </a>
                    <span class="ml-2 text-white width-100 text-center font-size-30">{{ $channel->title }}</span>
                    <div class="btn-group-lg m-3">
                        @can('follow',$channel)
                            <a href="{{ route('follow.channel',$channel->title)  }}" class="btn btn-lg btn-primary">Follow {{ $channel->follow }}</a>
                        @else
                            @can('authorUnfollow',$channel)
                                <a href="{{ route('unfollow.channel',$channel->title)  }}"
                                   class="btn btn-lg btn-primary">unFollow {{ $channel->follow }}</a>
                            @endcan
                        @endcan
                        <a href="{{ $channel->website }}" class="btn btn-lg btn-info">WebSite</a>
                    </div>
                </div>


            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link {{ (url()->current() == url("u/{$channel->user->name}") ?  'list-group-item-action': '' ) }}"
                       href="{{ route('channel',['name'=>$channel->user->name]) }}">Latest</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ (url()->current() == url("u/{$channel->user->name}/mostview") ?  'list-group-item-action': '' ) }}"
                       href="{{ route('channel.mostview',['name'=>$channel->user->name]) }}">Most viewed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ (url()->current() == url("u/{$channel->user->name}/mostlike") ?  'list-group-item-action': '' ) }}"
                       href="{{ route('channel.mostlike',['name'=>$channel->user->name]) }}">Most Liked</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ (url()->current() == url("u/{$channel->user->name}/mostlike") ?  'list-group-item-action': '' ) }}"
                       href="{{ route('channel.mostlike',['name'=>$channel->user->name]) }}">Followers</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row m-3">
            @foreach($videos as $item)
                <div class="col-md-2 text-center">
                    <div class="card-body">
                        <div class="position-relative">
                            <a href="{{ url("p/{$item->slug}") }}"><img width="100%" class="box-shadow-light" height="100%" src="{{ url($item->images) }}" alt="">
                                <time
                                    class="position-absolute top-0 left-0 bg-info text-white p-1">{{ $item->time }}</time>
                            </a>
                            <a href="{{ url("p/{$item->slug}") }}"><h4 class="text-body">{{ mb_substr($item->title,0,10) }}</h4></a>
                            <p>{{ mb_substr($item->description,0,20) . '...' }}</p>
                            @can("st_video",$item)
                                <form method="post" action="{{ url()->to("panel/video/{$item->id}") }}">
                                    @csrf
                                    {{ method_field("DELETE") }}
                                    <a href="{{url("panel/video/{$item->id}")}}" class="btn btn-info">Edit</a>
                                    <button type="submit" class="btn btn-danger">delete</button>
                                </form>
                            @endcan
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@stop
@section('content')
@stop

resources/views/panelUser/followings.blade.php
@extends('master')
@section('content')
    <div class="container mt-3">
        <div class="row">
{{--            @dd(auth()->user())--}}
            @foreach($allFollowings as $item)
                <div class="box-shadow-light col-4 card card-body mb-3 p-2">
                    <a href="{{ url("panel/video/$item->title") }}"></a>
                    <a class="mt-3" href="{{ url("panel/video/$item->id") }}"><h2
                            class="card-title text-dark d-inline">{{ $item->title }}</h2></a>
                    <div class="card-text">
                        <p>{{ mb_substr($item->description,0,20) . '....' }}</p>
                        <a href="{{ url("panel/video/{$item->id}") }}" class="btn btn-dark">Read the Doc</a>

                    </div>
                </div>
            @endforeach
        </div>
    </div>
@stop

resources/views/panelUser/show.blade.php
@extends('master')
@section('content')
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/dropzone.js"></script>
    <script>
        Dropzone.options.videoUpload = {
            dictDefaultMessage: 'Drop here bitch',
            maxFiles: 1,
            success(file, res) {
                alert('Upload successfully');
                $("#time").val(res.videoTime);
                $("#video").val(res.videoUrl);
                $("#images").val(res.imageUrl);
            }
        }
    </script>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="card card-body">
                    @include('auth.errors')
                    <div class="img card-img-top">
                        <img width="100" height="100" class="width-25p" src="{{ url($video->images) }}" alt="">
                        <form id="videoUpload" action="{{ route('panel.video.upload') }}"
                              class="dropzone width-75p float-right">
                            @csrf
                        </form>
                    </div>
                    <!--صهاهاقهصاهاشهاا-->
                    <!--these are for todo-->
                    <form method="post" action="{{route('video.update',['id'=>$video->id])}}">
                        <input type="hidden" value="" name="video" id="video">
                        @csrf
                        <input type="hidden" value="" id="time" name="time">
                        <input type="hidden" value="" id="images" name="images">
                        {{ method_field('patch') }}
                        <div class="form-group">
                            <label for="title">Title: </label>
                            <input type="text" id="title" value="{{ old('title',$video->title) }}" name="title"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="title">Custom Slug: </label>
                            <input type="text" id="slug" value="{{ $video->slug }}" name="slug" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="tags">Tags (seprate them with comma (,)): </label>
                            <input type="text" id="tags" value="{{ $video->tags }}" name="tags" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="tags">does users Can comment: </label>
                            <label for="">Can comment<input type="radio"
                                                            {{ $video->can_comment == 0 ? 'checked': ''}} id="can_comment"
                                                            name="can_comment" value="0"
                                                            class="form-check-inline"></label>
                            <label for="">Can't comment<input type="radio" id="can_comment"
                                                              {{ $video->can_comment == 1 ? 'checked': ''}}  name="can_comment"
                                                              value="1" class="form-check-inline"></label>
                        </div>

                        <div class="form-group">
                            <label for="description">description: </label>
                            <textarea type="text" id="description" name="description"
                                      class="form-control">{{ $video->description }}</textarea>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger">Submit data</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-body">
                    <h2 class="h4">
                        <p>This is a simple test for this page</p>
                    </h2>
                    <ul class="list-group">
                        @foreach($videos as $vid)
                            <a href="{{ url("panel/video/{$vid->id}") }}"><li class="p-1 list-group-item list-group-item-action"><img width="50px" height="50px" src="{{ url($vid->images) }}" class="br-10 mr-1 d-inline" alt="">{{ $vid->title  }}</li></a>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/panelUser/upload.blade.php
@extends('master')
@section('content')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/min/dropzone.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.4.0/dropzone.js"></script>
    <script>
        $(function () {
            Dropzone.options.videoUpload = {
                maxFilesize: 20, //MB
                paramName: 'file',
                dictDefaultMessage: "drop here",
                success: function (file, response) {
                    console.log(response.videoTime);
                    $("#time").val(response.videoTime);
                    $("#videoUrl").val(response.videoUrl);
                    $("#imageUrl").val(response.imageUrl);
                }
            }
        });

    </script>
    <main role="main" class="container">
        <div class="jumbotron">
            <h1>User Panel</h1>
            <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you
                scroll,
                this navbar remains in its original position and moves with the rest of the page.</p>
        </div>
    </main>
    <section id="tabs" class="project-tab">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <nav>
                        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                               role="tab" aria-controls="nav-home" aria-selected="true">Project Tab 1</a>
                            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile"
                               role="tab" aria-controls="nav-profile" aria-selected="false">Project Tab 2</a>
                            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact"
                               role="tab" aria-controls="nav-contact" aria-selected="false">Project Tab 3</a>
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel"
                             aria-labelledby="nav-home-tab">
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="formVid mt-3">
                                        <p class="text-left h3">Upload video here</p>
                                        <form id="videoUpload" action="{{ route('panel.video.upload') }}" method="POST"
                                              class="dropzone">
                                            @csrf
                                        </form>
                                    </div>
                                    @include('auth.errors')
                                </div>
                                <div class="col-md-7">
                                    <div class="formText mt-3">
                                        <form method="post" action="{{ route('video.store') }}" class="form-group">
                                            @csrf
                                            <input type="hidden" class="form-control" id="time" name="time">
                                            <input type="hidden" class="form-control" id="videoUrl" name="videoUrl">
                                            <input type="hidden" class="form-control" id="imageUrl" name="imageUrl">
                                            <input type="hidden" class="form-control" id="channel_id" value="{{ auth()->user()->channel->id }}" name="channel_id">
                                            <div class="form-group">
                                                <label for="title">Title</label>
                                                <input type="text" class="form-control" id="title" name="title">
                                            </div>
                                            <div class="form-group">
                                                <label for="description">description</label>
                                                <textarea class="form-control" id="description"
                                                          name="description"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label for="tags">tags</label>
                                                <input type="text" class="form-control" id="tags" name="tags">
                                            </div>
                                            <div class="form-group">

                                                <label for="Category">Select a category</label>
                                                <select name="category" class="form-control" id="Category">
                                                    @foreach($categories as $category)
                                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="comment">Comment</label>
                                                <select class="form-control" name="comment" id="comment">
                                                    <option value="1">Yes</option>
                                                    <option value="0">No</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-danger" type="submit">Send</button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            <table class="table" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Project Name</th>
                                    <th>Employer</th>
                                    <th>Time</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><a href="#">Work 1</a></td>
                                    <td>Doe</td>
                                    <td>john@example.com</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Work 2</a></td>
                                    <td>Moe</td>
                                    <td>mary@example.com</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Work 3</a></td>
                                    <td>Dooley</td>
                                    <td>july@example.com</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                            <table class="table" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Contest Name</th>
                                    <th>Date</th>
                                    <th>Award Position</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><a href="#">Work 1</a></td>
                                    <td>Doe</td>
                                    <td>john@example.com</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Work 2</a></td>
                                    <td>Moe</td>
                                    <td>mary@example.com</td>
                                </tr>
                                <tr>
                                    <td><a href="#">Work 3</a></td>
                                    <td>Dooley</td>
                                    <td>july@example.com</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

resources/views/panelUser/userPosts.blade.php
@extends('master')
@section('content')
    <div class="container mt-3">
        <div class="row">
            @foreach($allUrPosts as $item)
                <div class="box-shadow-light col-4 card card-body mb-3 p-2  ">
                    <a href="{{ url("panel/video/$item->id") }}"><img class="card-img-top d-inline"
                                                                      src="{{ url("{$item->images}") }}"
                                                                      alt="{{ $item->title }}"></a>
                    <a class="mt-3" href="{{ url("panel/video/$item->id") }}"><h2
                            class="card-title text-dark d-inline">{{ $item->title }}</h2></a>
                    <div class="card-text">
                        <p>{{ mb_substr($item->description,0,20) . '....' }}</p>
                        <a href="{{ url("panel/video/{$item->id}") }}" class="btn btn-dark">Read the Doc</a>
                        @can('st_video',$item)
                            <form class="form-group mt-1" method="post" action="{{ url()->to("panel/video/$item->id") }}">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button class="btn btn-danger" type="submit">Delete</button>
                                <a href="{{ url()->to("/panel/video/{$item->id}") }}" class="btn btn-info">Edit</a>
                            </form>
                            <p></p>
                        @endcan
                    </div>
                </div>
            @endforeach
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.0.6/sweetalert.min.js"></script>

    </div>
@stop